apiVersion: skaffold/v2alpha3 
kind: Config 
deploy: 
  kubectl: 
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev
build:
  googleCloudBuild:
    projectId: ticketing-dev-293022
  artifacts:
    - #image: aaronpazm/auth
      image: us.gcr.io/ticketing-dev-293022/auth
      context: auth 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - #image: aaronpazm/client
      image: us.gcr.io/ticketing-dev-293022/client
      context: client 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - #image: aaronpazm/tickets
      image: us.gcr.io/ticketing-dev-293022/tickets
      context: tickets 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - #image: aaronpazm/orders
      image: us.gcr.io/ticketing-dev-293022/orders
      context: orders 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - #image: aaronpazm/expiration
      image: us.gcr.io/ticketing-dev-293022/expiration
      context: expiration 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - #image: aaronpazm/payments
      image: us.gcr.io/ticketing-dev-293022/payments
      context: payments 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: '**/*.ts'
            dest: .