name: deploy-manifests 

on: 
  push:
    branches:
      - master # a merge into master counts as a push
    paths:
      - 'ticketing/infra/**' # only run if there is a change in the auth directory
      
jobs:
  build:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f ticketing/infra/k8s && kubectl apply -f ticketing/infra/k8s-prod
