name: deploy-tickets 

on: 
  push:
    branches:
      - master # a merge into master counts as a push
    paths:
      - 'ticketing/tickets/**' # only run if there is a change in the tickets directory
      
jobs:
  build:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - run: cd ticketing/tickets && docker build -t aaronpazm/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }} 
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}   
      - run: docker push aaronpazm/tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment tickets-depl